CREATE TABLE estructura_presupuestaria (
    id SERIAL PRIMARY KEY,
    cod_programa VARCHAR(10),
    desc_programa VARCHAR(255),
    cod_subprograma VARCHAR(10),
    desc_subprograma VARCHAR(255),
    cod_proyecto VARCHAR(15),
    desc_proyecto VARCHAR(255),
    cod_actividad VARCHAR(20),
    desc_actividad VARCHAR(255),
    cod_fuente VARCHAR(10),
    desc_fuente VARCHAR(255),
    cod_ubicacion VARCHAR(10),
    desc_ubicacion VARCHAR(255),
    cod_item VARCHAR(20),
    desc_item VARCHAR(255),
    codigo_completo VARCHAR(255),
    cod_organismo VARCHAR(10),
    desc_organismo VARCHAR(255),
    cod_nprest VARCHAR(10),
    desc_nprest VARCHAR(255)
);
